version: '3.6'
services:

  app:
    build: .
    image: stratos/ris-usecase
    volumes:
      - ./input:/data/input
      - ./output:/data/output
      - ./code:/code
    working_dir: /code
    command: ["python", "volume.py"]
